// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbYqA5a5A909OSl2-dLHaZjDv9NMwxVSE',
    appId: '1:99858215511:web:4a76549956644870db2912',
    messagingSenderId: '99858215511',
    projectId: 'fr-travel',
    authDomain: 'fr-travel.firebaseapp.com',
    storageBucket: 'fr-travel.firebasestorage.app',
    measurementId: 'G-QSJJ8JSHLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZihZgjYA6NUilyYLpRBq-wKh9hz9r1uw',
    appId: '1:99858215511:android:3dc6139c1eb0987ddb2912',
    messagingSenderId: '99858215511',
    projectId: 'fr-travel',
    storageBucket: 'fr-travel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmy29FahKM8SPe_ROdyVsvVN4r1uIyqik',
    appId: '1:99858215511:ios:7299de3d5ae8491adb2912',
    messagingSenderId: '99858215511',
    projectId: 'fr-travel',
    storageBucket: 'fr-travel.firebasestorage.app',
    iosBundleId: 'com.example.frTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmy29FahKM8SPe_ROdyVsvVN4r1uIyqik',
    appId: '1:99858215511:ios:7299de3d5ae8491adb2912',
    messagingSenderId: '99858215511',
    projectId: 'fr-travel',
    storageBucket: 'fr-travel.firebasestorage.app',
    iosBundleId: 'com.example.frTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbYqA5a5A909OSl2-dLHaZjDv9NMwxVSE',
    appId: '1:99858215511:web:7feb4870083fa716db2912',
    messagingSenderId: '99858215511',
    projectId: 'fr-travel',
    authDomain: 'fr-travel.firebaseapp.com',
    storageBucket: 'fr-travel.firebasestorage.app',
    measurementId: 'G-Z7XTG630KF',
  );
}
